ai:
  model: qwen/qwen3-coder-30b
  temperature: 0.3
  url: http://127.0.0.1:1234/v1/chat/completions
github:
  auto_create: false
  enabled: true
  owner: AlexisVS
  repo_name: test-weather-app-ia-orchestrator
  token: "${GITHUB_TOKEN}"
project:
  description: App meteo complete avec tous criteres
  name: weather-app-complete
  output_dir: C:/Users/alexi/weather-app-fresh
  type: nextjs
